language: bash

sudo: required

services:
- docker

env:
  global:
    - secure: ObaAi/JMIMZMeYnvTRSlwRmeRhctzyNmMlzIrH0VQAilEuAAfR7rWs6eClDBhy7ZgJlPjqt7psi+CQIVSvcvgg9rfMawWKOLcmHsVFOyw5YAdFnrQiU/nN/Z2220HECr75LpVE0wqZgpBsGA1NJkwJcx5xy3IhvOGHiN881jXBOhnbs9rpWJlP5Dft5RP3R78mG6KvrsWs0Cj6DuuSKOenRBZEjfN0t4V4ZcpJ6jBmKYEspGjp2IpGSMBw4FHjvPiMoppAQw/eyyNwpwpzjTbft6GGYFmQOVFDhaAHUfphUo7TwTztHNjjYbKbBnea8VgI1jEZ0Ov/jyHkd4j2wfgsIYXLMUjKvV2vHh09KgAEffD/X6rhvXQcvsv2bc5Gm3bGd8/VhjhBDaK7ZJ/H2fsptZ/zDU7135diV6s4Tq2ODDX1YNBlg2/Q1bhgq2tUY/ij9yojmlp9F73TP/F8exnGmhWRv/AOixFjnZsA5us7xQC6Y8FWgjb2vOSdpTLr92C67F04/1lHARoFdDx47bIf6tNOsJFr57sAf2Vg5dOK7sHNZuNYq/Nxgd4BtT9M1cAy/if/o08HQ+WekNdI8osSXUTecPyZTSfJ8VvhZfjGBbtt4ry9SHPUw0DXCq5M6gYPKGVYFVqlDs2TNL3euun1eVhXwm30owg+J8j6ffu2E=
    - secure: ErA0bU5Q0mrmQjvOqKhmzgR93m+tkCbrR6dnbtj294DcKA5ORmIVWi+cqIVtnbvqUu924b8ybu8Tl0mybM70fY0hBfJXJH6uMKFTMnilWM4SLQ00vp4RQs0K085dPwLBeYi0LxaLfY1/hzZJWwME3FLw82F8ld3y6c+4tAlJFP6ovcmUBdonZ8SeFcPQQSfQs0nGBQGvBaeXwqQLKpAlCmW0ZEMXFIVOebi9Dd4oPH5257nKmHXf4w2PKxzZAQG4xGh+q9pf7BWJ+F3YcjPTO5/e4EDXBTkQYvytivlEFT0dLMPGBUPwIFHtWWRKEVBCTgB4XnXCIICAKpIomAwUkWVMlI0VVCMH+ieGdthPi1AprXkCx8EEqChG0Gts/BWCWPqKCXYGdcLIPnTS6U8C3jqGovv6IeSk0xjVOaO7J+utH3oTIgZZVD7MD5hXN6xNy0AJF64FZG6geAmBvPQSpVpLdhjxzGO5RE6BqiS8dSOhPG3M9CoIdSu7RuT5yQyH+/C++q3KAzXkWNIV2SrEjdRjunwY7C3jm8avxlH83YBNKzEnCp8y5A49/aZieNYUd/iWLISQq0BzL0OJkpEYQluTkRJyJ9t+p9An/SA7TV5Befb/LU2pyxYHlGr7Tc/amNd6rmFoO5smyAPRqVnt1EFg6x8Oy0svx5umREqGmLM=
    - secure: fBUNWbMUGR/sw2hg8iaRWR4JUQT4fhxhOVZPZeI3MWMqv3RNr0XIthlXiAkU/mDH3hNPrVHv86QybgbqsXLNvwpOVhIXx+DmHV/O3PO3fX2FXc/7yocpI7/bogfwWK9w197ans1uTD7dpq512/T+RH03zip6huvD0Y5aNpElSeYYMevB5isEL3Y/Gjw8OQVBYX+tVL6tCf/kU4ClcviWEfuLS473RHszyEdiRSdgP04TwJ6OMnSVaDYechTomeMrZDDdmoezxkb2SpK0FOLfcfRaYC4VpGrHnkG+tGYYK7oNph9hfkDKD5xXi/6Tovb2Sc3zYQzOKBorKzbkmhOTbl+f26aAlcBw4TnHuC8/uqxOm1ZoRCa7rAF2kNXBwHtRhBv0Zva25KRFYXXzV4HS1FBnvMD8x+d7xSp5izdeWbYjAqJiNMJnkIzukVzT42WIwygv/PtogDpDISMZdT7CjsOpfCgpx5btQZfxHeNmAb3TegxaLMS7X4Yy5ZElANShe3x/Tkus2uzayZQ0rb5w78TZsGDiuW7DwmFgYnSHqrJMnLia4mZpwJqwjlq1ubXlEcHILlUguEQwGmEgfYHR1rtdl8tHfK8bL6rjPSmwQwnpn3Gnbq4WQT5XkUKxrbN6saCHEDHDELAr997q59GCwM1jt0cbG/7SJoeFMHw0TRM=
    - REPOSITORY="encodeering"
  matrix:
    - PROJECT="joomla" BASE=debian ARCH=amd64 VERSION=3.9 VARIANT=fpm
    - PROJECT="joomla" BASE=debian ARCH=armhf VERSION=3.9 VARIANT=fpm
    - PROJECT="joomla" BASE=alpine ARCH=amd64 VERSION=3.9 VARIANT=nginx
    - PROJECT="joomla" BASE=alpine ARCH=armhf VERSION=3.9 VARIANT=nginx

install:
- bash <(curl https://raw.githubusercontent.com/encodeering/docker-ci/master/install.sh) 0.1.11

before_script:
- sudo -E bash ./module.sh "." "./setup.sh"

script:
- sudo -E bash ./module.sh "modules" "./build.sh"

after_script:
- docker images

deploy:
  script: sudo -E bash ./module.sh "." "./release.sh"
  provider: script
  skip_cleanup: true
  on:
    all_branches: true
