version: '3.5'
services:
  traefik:
    image: encodeering/traefik-${ARCH:-armhf}:2.11-alpine
    command:
      - --log.level=INFO
      - --entryPoints.https.address=:443
      - --entryPoints.http.address=:80
      - --entryPoints.http.http.redirections.entryPoint.to=https
      - --entryPoints.http.http.redirections.entryPoint.scheme=https
      - --providers.docker.watch=true
      - --providers.docker.exposedByDefault=false
      - --certificatesResolvers.default.acme.email=${EMAIL}
      - --certificatesResolvers.default.acme.httpChallenge.entrypoint=http
      - --certificatesResolvers.default.acme.storage=/data/acme.json
    volumes:
      - proxy:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
    networks:
      traefik:

  nginx:
    image: encodeering/joomla-${ARCH:-armhf}:${VERSION:-5.1}-alpine-nginx
    volumes:
      - www:/var/www/html
    depends_on:
      - joomla
    environment:
      VHOST: ssl-off-h2c
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.joomla.entrypoints: http
      traefik.http.routers.joomla.rule: Host(`${DOMAIN}`) # && Headers(`X-Bootstrap`, `f22c97f5-eaf3-458d-b483-1df930a56022`) # useful during a bootstrap event if you can't shield the process in another way, but requires a browser extension. please use a different value and remove it afterward
      traefik.http.routers.joomla-secure.rule: Host(`${DOMAIN}`) # && Headers(`X-Bootstrap`, `f22c97f5-eaf3-458d-b483-1df930a56022`)
      traefik.http.routers.joomla-secure.tls: true
      traefik.http.routers.joomla-secure.tls.certresolver: default
      traefik.http.routers.joomla-secure.service: joomla
      traefik.http.services.joomla.loadbalancer.server.port: 80
      traefik.http.services.joomla.loadbalancer.server.scheme: h2c
    networks:
      joomla:
      traefik:

  joomla:
    image: encodeering/joomla-${ARCH:-armhf}:${VERSION:-5.1}-alpine-fpm-sequel
    volumes:
      - www:/var/www/html
    depends_on:
      - postgres
    networks:
      joomla:
        aliases:
          - php

  postgres:
    image: encodeering/postgres-${ARCH:-armhf}:16-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: joomla
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${SECRET:-secret}
    networks:
      joomla:

volumes:
  www:
  db:
  proxy:

networks:
  joomla:
    name: joomla
  traefik:
    name: traefik
